name: "test"
task: "p2p_dtm"
dataset_name: "RISys-Lab/TRIG"

# legacy JSON is also supported
# prompt_path: "/home/muzammal/Projects/TRIG/dataset/Trig/Trig-image-editing/p2p.json"
# image_path: "/home/muzammal/Projects/TRIG/dataset/Trig/Trig-image-editing/images"
# description_path: "/home/muzammal/Projects/TRIG/dataset/Trig/Trig-image-editing/image_descriptions.json"

generation:
  models: ["hqedit_dtm_dim"]
